services:
  db:
    image: postgres:15-alpine
    container_name: certificates_db
    restart: always
    environment:
      POSTGRES_DB: certificates_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: certificates_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=certificates_db
      - DB_USER=django_user
      - DB_PASSWORD=django_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: